// [임시] Mock API 대응용 레시피 데이터
// TODO: 백엔드 API 완성 후 제거

export const mockRecipes = {
  601: {
    recipeId: 601,
    title: "돼지고기 김치찌개",
    description: "한국인의 소울푸드, 얼큰하고 시원한 김치찌개",
    thumbnail:
      "https://images.unsplash.com/photo-1604917017367-4b89d70e4b0a?w=300&h=200&fit=crop",
    cookTime: "30분",
    difficulty: "중급",
    matchRate: 85,
    ingredients: ["돼지고기", "김치", "두부", "양파"],
    servings: "2인분",
    steps: [
      { order: 1, content: "김치와 돼지고기를 먹기 좋은 크기로 썬다." },
      { order: 2, content: "냄비에 기름을 두르고 김치와 고기를 볶는다." },
      { order: 3, content: "물을 넣고 끓인 후 두부와 양파를 넣어 완성한다." },
    ],
  },
  602: {
    recipeId: 602,
    title: "김치 제육볶음",
    thumbnail:
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=300&h=200&fit=crop",
    cookTime: "20분",
    difficulty: "초급",
    matchRate: 92,
    ingredients: ["돼지고기", "김치", "고춧가루", "대파"],
    servings: "2인분",
    steps: [
      { order: 1, content: "돼지고기를 한입 크기로 썰고 김치는 송송 썬다." },
      { order: 2, content: "팬에 기름을 두르고 돼지고기를 먼저 볶는다." },
      {
        order: 3,
        content: "고기가 익으면 김치와 고춧가루를 넣고 함께 볶는다.",
      },
      { order: 4, content: "마지막에 대파를 넣고 한번 더 볶아 완성한다." },
    ],
  },
  603: {
    recipeId: 603,
    title: "크림 리소토",
    thumbnail:
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=300&h=200&fit=crop",
    cookTime: "35분",
    difficulty: "중급",
    matchRate: 70,
    ingredients: ["쌀", "크림", "버섯", "파마산 치즈"],
    servings: "2인분",
    steps: [
      { order: 1, content: "버섯을 슬라이스하고 양파를 잘게 다진다." },
      { order: 2, content: "팬에 버터를 녹이고 양파와 버섯을 볶는다." },
      { order: 3, content: "쌀을 넣고 투명해질 때까지 볶는다." },
      { order: 4, content: "육수를 조금씩 부으며 저어가며 익힌다." },
      { order: 5, content: "크림과 파마산 치즈를 넣어 부드럽게 마무리한다." },
    ],
  },
  604: {
    recipeId: 604,
    title: "떡볶이",
    thumbnail:
      "https://images.unsplash.com/photo-1604917017367-4b89d70e4b0a?w=300&h=200&fit=crop",
    cookTime: "15분",
    difficulty: "초급",
    matchRate: 95,
    ingredients: ["떡", "고추장", "어묵", "대파"],
    servings: "2인분",
    steps: [
      { order: 1, content: "떡은 찬물에 담가 불리고 어묵은 먹기 좋게 자른다." },
      { order: 2, content: "냄비에 물과 고추장, 설탕을 넣고 끓인다." },
      { order: 3, content: "끓으면 떡과 어묵을 넣고 중불에서 끓인다." },
      { order: 4, content: "떡이 부드러워지면 대파를 넣어 마무리한다." },
    ],
  },
  605: {
    recipeId: 605,
    title: "초밥 세트",
    thumbnail:
      "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=300&h=200&fit=crop",
    cookTime: "60분",
    difficulty: "고급",
    matchRate: 55,
    ingredients: ["밥", "생선회", "김", "와사비"],
    servings: "2인분",
    steps: [
      { order: 1, content: "밥에 초밥 식초를 섞어 식힌다." },
      { order: 2, content: "생선회를 초밥용으로 얇게 썬다." },
      { order: 3, content: "밥을 손에 쥐고 타원형으로 뭉친다." },
      { order: 4, content: "와사비를 살짝 바르고 생선회를 올린다." },
      { order: 5, content: "김으로 감싸거나 그대로 접시에 담는다." },
    ],
  },
  606: {
    recipeId: 606,
    title: "치킨 커리",
    thumbnail:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=300&h=200&fit=crop",
    cookTime: "40분",
    difficulty: "중급",
    matchRate: 78,
    ingredients: ["닭고기", "커리", "감자", "당근", "양파"],
    servings: "2인분",
    steps: [
      {
        order: 1,
        content: "닭고기는 한입 크기로, 감자와 당근은 큼직하게 썬다.",
      },
      { order: 2, content: "냄비에 기름을 두르고 양파를 볶는다." },
      { order: 3, content: "닭고기를 넣고 겉면이 익을 때까지 볶는다." },
      { order: 4, content: "감자, 당근을 넣고 물을 부어 끓인다." },
      { order: 5, content: "야채가 익으면 커리 루를 넣고 녹여 완성한다." },
    ],
  },
  607: {
    recipeId: 607,
    title: "새우 볶음밥",
    thumbnail:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=300&h=200&fit=crop",
    cookTime: "25분",
    difficulty: "초급",
    matchRate: 88,
    ingredients: ["밥", "새우", "계란", "대파", "간장"],
    servings: "2인분",
    steps: [
      { order: 1, content: "새우는 손질하고 대파는 송송 썬다." },
      { order: 2, content: "팬에 기름을 두르고 계란을 스크램블한다." },
      { order: 3, content: "새우를 넣고 빠르게 볶는다." },
      { order: 4, content: "밥을 넣고 간장으로 간하며 볶는다." },
      { order: 5, content: "대파를 넣고 한번 더 볶아 완성한다." },
    ],
  },
  608: {
    recipeId: 608,
    title: "스파게티 카르보나라",
    thumbnail:
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=300&h=200&fit=crop",
    cookTime: "20분",
    difficulty: "중급",
    matchRate: 82,
    ingredients: ["파스타면", "베이컨", "계란", "파마산 치즈", "후추"],
    servings: "2인분",
    steps: [
      { order: 1, content: "베이컨을 작게 썰고 계란 노른자와 치즈를 섞는다." },
      { order: 2, content: "파스타 면을 삶아 건져낸다." },
      { order: 3, content: "팬에 베이컨을 바삭하게 볶는다." },
      { order: 4, content: "불을 끄고 면을 넣어 섞는다." },
      { order: 5, content: "계란 치즈 혼합물을 넣고 빠르게 저어 완성한다." },
    ],
  },
  609: {
    recipeId: 609,
    title: "된장국",
    thumbnail:
      "https://images.unsplash.com/photo-1604917017367-4b89d70e4b0a?w=300&h=200&fit=crop",
    cookTime: "10분",
    difficulty: "초급",
    matchRate: 98,
    ingredients: ["된장", "두부", "호박", "대파", "멸치육수"],
    servings: "2인분",
    steps: [
      { order: 1, content: "멸치육수를 끓이고 된장을 푼다." },
      { order: 2, content: "두부와 호박을 적당한 크기로 썬다." },
      { order: 3, content: "끓는 국물에 두부와 호박을 넣고 끓인다." },
      { order: 4, content: "마지막에 대파를 넣어 마무리한다." },
    ],
  },
  610: {
    recipeId: 610,
    title: "갈비탕",
    thumbnail:
      "https://images.unsplash.com/photo-1604917017367-4b89d70e4b0a?w=300&h=200&fit=crop",
    cookTime: "90분",
    difficulty: "고급",
    matchRate: 62,
    ingredients: ["소갈비", "무", "대파", "마늘", "후추"],
    servings: "4인분",
    steps: [
      { order: 1, content: "소갈비를 찬물에 담가 핏물을 뺀다." },
      { order: 2, content: "끓는 물에 소갈비를 넣고 한소끔 삶아 건진다." },
      {
        order: 3,
        content: "새 물에 갈비와 무, 마늘을 넣고 1시간 이상 푹 끓인다.",
      },
      { order: 4, content: "대파와 후추로 간하고 마무리한다." },
    ],
  },
  611: {
    recipeId: 611,
    title: "불고기",
    thumbnail:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=300&h=200&fit=crop",
    cookTime: "30분",
    difficulty: "중급",
    matchRate: 87,
    ingredients: ["소고기", "양파", "대파", "당근", "간장", "설탕"],
    servings: "3인분",
    steps: [
      { order: 1, content: "소고기를 얇게 썰고 양파, 당근, 대파를 준비한다." },
      {
        order: 2,
        content: "간장, 설탕, 다진 마늘, 참기름을 섞어 양념장을 만든다.",
      },
      { order: 3, content: "소고기와 야채를 양념장에 버무려 30분 재운다." },
      { order: 4, content: "팬에 재운 고기를 넣고 중불에서 볶아 완성한다." },
    ],
  },
  612: {
    recipeId: 612,
    title: "오이냉국",
    thumbnail:
      "https://images.unsplash.com/photo-1604917017367-4b89d70e4b0a?w=300&h=200&fit=crop",
    cookTime: "5분",
    difficulty: "초급",
    matchRate: 90,
    ingredients: ["오이", "식초", "설탕", "소금"],
    servings: "2인분",
    steps: [
      { order: 1, content: "오이를 얇게 슬라이스한다." },
      { order: 2, content: "물에 식초, 설탕, 소금을 넣어 육수를 만든다." },
      { order: 3, content: "오이를 육수에 담가 차게 식혀 완성한다." },
    ],
  },
  613: {
    recipeId: 613,
    title: "마라탕",
    thumbnail:
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=300&h=200&fit=crop",
    cookTime: "25분",
    difficulty: "중급",
    matchRate: 73,
    ingredients: ["당면", "양고기", "배추", "마라소스", "고추"],
    servings: "2인분",
    steps: [
      { order: 1, content: "당면을 찬물에 불리고 양고기와 배추를 썬다." },
      { order: 2, content: "냄비에 물을 끓이고 마라소스를 넣는다." },
      { order: 3, content: "양고기와 배추를 넣고 익힌다." },
      { order: 4, content: "당면과 고추를 넣고 한소끔 끓여 완성한다." },
    ],
  },
  614: {
    recipeId: 614,
    title: "계란말이",
    thumbnail:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=300&h=200&fit=crop",
    cookTime: "10분",
    difficulty: "초급",
    matchRate: 94,
    ingredients: ["계란", "대파", "소금", "식용유"],
    servings: "1인분",
    steps: [
      { order: 1, content: "계란을 풀고 대파를 잘게 썰어 넣는다." },
      {
        order: 2,
        content: "팬에 기름을 두르고 계란물을 부어 약불에서 익힌다.",
      },
      { order: 3, content: "계란이 반쯤 익으면 돌돌 말아가며 익힌다." },
      { order: 4, content: "먹기 좋은 크기로 썰어 완성한다." },
    ],
  },
  615: {
    recipeId: 615,
    title: "샐러드",
    thumbnail:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=300&h=200&fit=crop",
    cookTime: "5분",
    difficulty: "초급",
    matchRate: 96,
    ingredients: ["양상추", "토마토", "오이", "드레싱"],
    servings: "1인분",
    steps: [
      { order: 1, content: "양상추를 한입 크기로 뜯고 찬물에 헹군다." },
      { order: 2, content: "토마토와 오이를 적당한 크기로 썬다." },
      { order: 3, content: "접시에 채소를 담고 드레싱을 뿌려 완성한다." },
    ],
  },
  616: {
    recipeId: 616,
    title: "토마토 파스타",
    thumbnail:
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=300&h=200&fit=crop",
    cookTime: "25분",
    difficulty: "중급",
    matchRate: 85,
    ingredients: ["파스타면", "토마토", "마늘", "올리브오일", "바질"],
    servings: "2인분",
    steps: [
      { order: 1, content: "파스타 면을 삶고 토마토는 큼직하게 자른다." },
      { order: 2, content: "팬에 올리브오일을 두르고 마늘을 볶는다." },
      { order: 3, content: "토마토를 넣고 으깨가며 소스를 만든다." },
      { order: 4, content: "삶은 면을 넣고 섞은 후 바질을 올려 완성한다." },
    ],
  },
  617: {
    recipeId: 617,
    title: "비빔밥",
    thumbnail:
      "https://images.unsplash.com/photo-1604917017367-4b89d70e4b0a?w=300&h=200&fit=crop",
    cookTime: "20분",
    difficulty: "중급",
    matchRate: 91,
    ingredients: ["밥", "고사리", "시금치", "당근", "계란", "고추장"],
    servings: "1인분",
    steps: [
      { order: 1, content: "고사리, 시금치, 당근을 각각 볶아 나물을 만든다." },
      { order: 2, content: "계란을 지단으로 부쳐 채썬다." },
      { order: 3, content: "그릇에 밥을 담고 나물과 계란을 예쁘게 올린다." },
      { order: 4, content: "고추장을 올리고 잘 비벼 먹는다." },
    ],
  },
  618: {
    recipeId: 618,
    title: "순두부찌개",
    thumbnail:
      "https://images.unsplash.com/photo-1604917017367-4b89d70e4b0a?w=300&h=200&fit=crop",
    cookTime: "15분",
    difficulty: "초급",
    matchRate: 93,
    ingredients: ["순두부", "김치", "고추가루", "대파", "계란"],
    servings: "1인분",
    steps: [
      { order: 1, content: "냄비에 물을 끓이고 김치와 고추가루를 넣는다." },
      { order: 2, content: "순두부를 넣고 중불에서 끓인다." },
      { order: 3, content: "계란을 풀어 넣고 대파를 올린다." },
      { order: 4, content: "한소끔 끓여 완성한다." },
    ],
  },
  619: {
    recipeId: 619,
    title: "닭볶음탕",
    thumbnail:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=300&h=200&fit=crop",
    cookTime: "50분",
    difficulty: "중급",
    matchRate: 80,
    ingredients: ["닭고기", "감자", "당근", "양파", "고추장", "간장"],
    servings: "3인분",
    steps: [
      {
        order: 1,
        content:
          "닭고기를 먹기 좋은 크기로 자르고 감자, 당근, 양파를 큼직하게 썬다.",
      },
      { order: 2, content: "고추장, 간장, 설탕, 다진 마늘로 양념장을 만든다." },
      { order: 3, content: "냄비에 닭고기와 양념장을 넣고 볶는다." },
      { order: 4, content: "물을 붓고 감자, 당근, 양파를 넣어 푹 끓인다." },
      { order: 5, content: "야채가 익으면 완성한다." },
    ],
  },
  620: {
    recipeId: 620,
    title: "감자튀김",
    thumbnail:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=300&h=200&fit=crop",
    cookTime: "20분",
    difficulty: "초급",
    matchRate: 89,
    ingredients: ["감자", "식용유", "소금"],
    servings: "2인분",
    steps: [
      {
        order: 1,
        content: "감자를 깨끗이 씻어 껍질을 벗기고 막대 모양으로 썬다.",
      },
      { order: 2, content: "찬물에 담가 전분을 빼고 물기를 완전히 제거한다." },
      { order: 3, content: "170도 기름에 넣어 노릇하게 튀긴다." },
      { order: 4, content: "기름을 빼고 소금을 뿌려 완성한다." },
    ],
  },
  621: {
    recipeId: 621,
    title: "라면",
    thumbnail:
      "https://images.unsplash.com/photo-1604917017367-4b89d70e4b0a?w=300&h=200&fit=crop",
    cookTime: "7분",
    difficulty: "초급",
    matchRate: 99,
    ingredients: ["라면", "계란", "대파", "김치"],
    servings: "1인분",
    steps: [
      { order: 1, content: "냄비에 물을 끓이고 수프와 면을 넣는다." },
      { order: 2, content: "김치와 대파를 넣고 끓인다." },
      { order: 3, content: "계란을 풀어 넣거나 통째로 넣어 익힌다." },
      { order: 4, content: "그릇에 담아 완성한다." },
    ],
  },
  622: {
    recipeId: 622,
    title: "잡채",
    thumbnail:
      "https://images.unsplash.com/photo-1604917017367-4b89d70e4b0a?w=300&h=200&fit=crop",
    cookTime: "35분",
    difficulty: "중급",
    matchRate: 84,
    ingredients: ["당면", "시금치", "당근", "표고버섯", "소고기", "간장"],
    servings: "3인분",
    steps: [
      { order: 1, content: "당면을 삶아 건지고 찬물에 헹군다." },
      { order: 2, content: "시금치, 당근, 버섯, 소고기를 각각 볶는다." },
      { order: 3, content: "당면에 간장, 설탕, 참기름을 넣고 버무린다." },
      { order: 4, content: "모든 재료를 섞어 완성한다." },
    ],
  },
  623: {
    recipeId: 623,
    title: "삼겹살 구이",
    thumbnail:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=300&h=200&fit=crop",
    cookTime: "15분",
    difficulty: "초급",
    matchRate: 97,
    ingredients: ["삼겹살", "상추", "마늘", "쌈장"],
    servings: "2인분",
    steps: [
      { order: 1, content: "삼겹살을 적당한 두께로 준비한다." },
      { order: 2, content: "팬이나 석쇠에 삼겹살을 올려 구워준다." },
      { order: 3, content: "마늘도 함께 구워 준비한다." },
      { order: 4, content: "상추에 삼겹살, 마늘, 쌈장을 올려 먹는다." },
    ],
  },
  624: {
    recipeId: 624,
    title: "피자 토스트",
    thumbnail:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=300&h=200&fit=crop",
    cookTime: "10분",
    difficulty: "초급",
    matchRate: 92,
    ingredients: ["식빵", "토마토소스", "치즈", "피망", "햄"],
    servings: "1인분",
    steps: [
      { order: 1, content: "식빵에 토마토소스를 골고루 바른다." },
      { order: 2, content: "햄과 피망을 얹고 치즈를 듬뿍 올린다." },
      {
        order: 3,
        content: "오븐이나 에어프라이어에 넣어 치즈가 녹을 때까지 굽는다.",
      },
      { order: 4, content: "먹기 좋게 잘라 완성한다." },
    ],
  },
  625: {
    recipeId: 625,
    title: "육개장",
    thumbnail:
      "https://images.unsplash.com/photo-1604917017367-4b89d70e4b0a?w=300&h=200&fit=crop",
    cookTime: "60분",
    difficulty: "고급",
    matchRate: 75,
    ingredients: ["소고기", "고사리", "대파", "고추가루", "계란"],
    servings: "2인분",
    steps: [
      { order: 1, content: "소고기를 삶아 찢어 준비하고 국물은 따로 둔다." },
      { order: 2, content: "고사리를 삶아 먹기 좋은 길이로 자른다." },
      { order: 3, content: "국물에 고추가루, 다진 마늘을 넣고 끓인다." },
      { order: 4, content: "소고기와 고사리를 넣고 푹 끓인다." },
      { order: 5, content: "대파를 넣고 마무리한다." },
    ],
  },
  626: {
    recipeId: 626,
    title: "냉면",
    thumbnail:
      "https://images.unsplash.com/photo-1604917017367-4b89d70e4b0a?w=300&h=200&fit=crop",
    cookTime: "20분",
    difficulty: "중급",
    matchRate: 86,
    ingredients: ["냉면", "오이", "계란", "육수", "식초", "겨자"],
    servings: "2인분",
    steps: [
      { order: 1, content: "냉면을 삶아 찬물에 여러 번 헹군다." },
      { order: 2, content: "육수를 차갑게 준비하고 식초와 겨자를 섞는다." },
      { order: 3, content: "오이를 채 썰고 계란은 반숙으로 삶는다." },
      {
        order: 4,
        content: "그릇에 면을 담고 육수를 붓고 토핑을 올려 완성한다.",
      },
    ],
  },
  627: {
    recipeId: 627,
    title: "감자전",
    thumbnail:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=300&h=200&fit=crop",
    cookTime: "25분",
    difficulty: "중급",
    matchRate: 83,
    ingredients: ["감자", "양파", "부침가루", "식용유"],
    servings: "2인분",
    steps: [
      { order: 1, content: "감자와 양파를 강판에 갈아 물기를 살짝 뺀다." },
      { order: 2, content: "부침가루를 넣고 섞어 반죽을 만든다." },
      { order: 3, content: "팬에 기름을 두르고 반죽을 얇게 펴서 부친다." },
      { order: 4, content: "양면이 노릇해지면 먹기 좋게 잘라 완성한다." },
    ],
  },
  628: {
    recipeId: 628,
    title: "김밥",
    thumbnail:
      "https://images.unsplash.com/photo-1604917017367-4b89d70e4b0a?w=300&h=200&fit=crop",
    cookTime: "30분",
    difficulty: "중급",
    matchRate: 88,
    ingredients: ["밥", "김", "계란", "단무지", "햄", "시금치"],
    servings: "2인분",
    steps: [
      { order: 1, content: "밥에 참기름과 소금을 넣고 섞는다." },
      { order: 2, content: "계란을 부쳐 채 썰고 햄은 볶고 시금치는 데친다." },
      { order: 3, content: "김에 밥을 펴고 재료를 일렬로 놓는다." },
      { order: 4, content: "돌돌 말아 먹기 좋게 썰어 완성한다." },
    ],
  },
  629: {
    recipeId: 629,
    title: "콩나물국",
    thumbnail:
      "https://images.unsplash.com/photo-1604917017367-4b89d70e4b0a?w=300&h=200&fit=crop",
    cookTime: "15분",
    difficulty: "초급",
    matchRate: 95,
    ingredients: ["콩나물", "대파", "마늘", "멸치육수", "고춧가루"],
    servings: "2인분",
    steps: [
      { order: 1, content: "멸치육수를 끓이고 콩나물을 넣는다." },
      { order: 2, content: "다진 마늘과 고춧가루를 넣는다." },
      { order: 3, content: "뚜껑을 덮고 5분간 끓인다." },
      { order: 4, content: "대파를 넣고 소금으로 간해 완성한다." },
    ],
  },
  630: {
    recipeId: 630,
    title: "치즈돈까스",
    thumbnail:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=300&h=200&fit=crop",
    cookTime: "30분",
    difficulty: "중급",
    matchRate: 81,
    ingredients: ["돼지고기", "치즈", "빵가루", "계란", "식용유"],
    servings: "2인분",
    steps: [
      {
        order: 1,
        content: "돼지고기를 두드려 얇게 펴고 소금, 후추로 밑간한다.",
      },
      { order: 2, content: "고기 사이에 치즈를 넣고 감싼다." },
      { order: 3, content: "밀가루, 계란, 빵가루 순으로 옷을 입힌다." },
      { order: 4, content: "170도 기름에 넣어 노릇하게 튀겨 완성한다." },
    ],
  },
};
